/**
 * GENERATED BY scripts/wave414-responsive-images.py. DO NOT EDIT BY HAND.
 *
 * Which widths of each photograph actually exist on disk, so a `srcset` can
 * never name a file that is not there. The script refuses any step that does
 * not come out smaller than its own source, so this map is the ONLY honest
 * record of what was written: a hand-typed `srcset` would 404 on the steps it
 * dropped, and a list of widths shared between the script and the components
 * would go stale the first time an encoder disagreed with it.
 *
 * Re-run the script after adding a photograph;
 * `python scripts/wave414-responsive-images.py --check` fails a build where
 * this file and the directory disagree.
 */

export const IMAGE_VARIANTS: Record<string, { steps: number[]; width: number; height: number }> = {
  "/images/ai-team/collective-capability-team.png": {
    steps: [400, 640],
    width: 934,
    height: 558,
  },
  "/images/ai-team/peter-present.webp": {
    steps: [],
    width: 281,
    height: 560,
  },
  "/images/ai-team/peter.webp": {
    steps: [],
    width: 272,
    height: 520,
  },
  "/images/ai-team/petra-point.webp": {
    steps: [],
    width: 338,
    height: 560,
  },
  "/images/ai-team/petra.webp": {
    steps: [],
    width: 347,
    height: 520,
  },
  "/images/ai-team/pippa-point.webp": {
    steps: [],
    width: 345,
    height: 560,
  },
  "/images/ai-team/pippa-present.webp": {
    steps: [],
    width: 271,
    height: 560,
  },
  "/images/ai-team/pippa.webp": {
    steps: [],
    width: 313,
    height: 520,
  },
  "/images/ai-team/trio-wave.webp": {
    steps: [400, 640],
    width: 934,
    height: 558,
  },
  "/images/brand/logo-lockup-reverse.webp": {
    steps: [400, 640, 960, 1440],
    width: 2006,
    height: 310,
  },
  "/images/brand/logo-lockup.webp": {
    steps: [400, 640, 960, 1440],
    width: 2006,
    height: 310,
  },
  "/images/brand/logo-mark-reverse.webp": {
    steps: [],
    width: 254,
    height: 264,
  },
  "/images/brand/logo-mark.webp": {
    steps: [],
    width: 254,
    height: 264,
  },
  "/images/brand/zoopla-ink.webp": {
    steps: [400],
    width: 548,
    height: 120,
  },
  "/images/chain/care.webp": {
    steps: [],
    width: 288,
    height: 288,
  },
  "/images/chain/lease.webp": {
    steps: [],
    width: 288,
    height: 288,
  },
  "/images/chain/source.webp": {
    steps: [],
    width: 288,
    height: 288,
  },
  "/images/ecosystem-band.jpg": {
    steps: [400, 640, 960, 1440],
    width: 1920,
    height: 640,
  },
  "/images/hero-ground-street.webp": {
    steps: [400, 640, 960],
    width: 1672,
    height: 941,
  },
  "/images/hero-homes.webp": {
    steps: [400, 640, 960],
    width: 1280,
    height: 1024,
  },
  "/images/hero-lives.webp": {
    steps: [400, 640, 960],
    width: 1280,
    height: 1024,
  },
  "/images/hero-support.webp": {
    steps: [400, 640, 960],
    width: 1280,
    height: 1024,
  },
  "/images/human-insight.jpg": {
    steps: [400, 640, 960, 1440],
    width: 1536,
    height: 1024,
  },
  "/images/human-meeting.jpg": {
    steps: [400, 640, 960, 1440],
    width: 1536,
    height: 1024,
  },
  "/images/human-partnership.jpg": {
    steps: [400, 640, 960],
    width: 1024,
    height: 1536,
  },
  "/images/logos/councils/normalised/county-durham.webp": {
    steps: [],
    width: 240,
    height: 104,
  },
  "/images/logos/councils/normalised/cumberland.webp": {
    steps: [],
    width: 240,
    height: 104,
  },
  "/images/logos/councils/normalised/derby.webp": {
    steps: [],
    width: 240,
    height: 104,
  },
  "/images/logos/councils/normalised/east-riding-of-yorkshire.webp": {
    steps: [],
    width: 240,
    height: 104,
  },
  "/images/logos/councils/normalised/hartlepool.webp": {
    steps: [],
    width: 240,
    height: 104,
  },
  "/images/logos/councils/normalised/lancashire.webp": {
    steps: [],
    width: 240,
    height: 104,
  },
  "/images/logos/councils/normalised/lincolnshire.webp": {
    steps: [],
    width: 240,
    height: 104,
  },
  "/images/logos/councils/normalised/liverpool.webp": {
    steps: [],
    width: 240,
    height: 104,
  },
  "/images/logos/councils/normalised/manchester.webp": {
    steps: [],
    width: 240,
    height: 104,
  },
  "/images/logos/councils/normalised/middlesbrough.webp": {
    steps: [],
    width: 240,
    height: 104,
  },
  "/images/logos/councils/normalised/newcastle.webp": {
    steps: [],
    width: 240,
    height: 104,
  },
  "/images/logos/councils/normalised/north-east-lincolnshire.webp": {
    steps: [],
    width: 240,
    height: 104,
  },
  "/images/logos/councils/normalised/nottingham.webp": {
    steps: [],
    width: 240,
    height: 104,
  },
  "/images/logos/councils/normalised/salford.webp": {
    steps: [],
    width: 240,
    height: 104,
  },
  "/images/logos/councils/normalised/stockton-on-tees.webp": {
    steps: [],
    width: 240,
    height: 104,
  },
  "/images/logos/councils/normalised/sunderland.webp": {
    steps: [],
    width: 240,
    height: 104,
  },
  "/images/logos/councils/normalised/westmorland-and-furness.webp": {
    steps: [],
    width: 240,
    height: 104,
  },
  "/images/logos/councils/normalised/wirral.webp": {
    steps: [],
    width: 240,
    height: 104,
  },
  "/images/partners/connected-network-broker.png": {
    steps: [400, 640, 960, 1440],
    width: 1672,
    height: 941,
  },
  "/images/partners/connected-network-care-provider.png": {
    steps: [400, 640, 960, 1440],
    width: 1672,
    height: 941,
  },
  "/images/partners/connected-network-developer.png": {
    steps: [400, 640, 960, 1440],
    width: 1672,
    height: 941,
  },
  "/images/partners/connected-network-housing-association.png": {
    steps: [400, 640, 960, 1440],
    width: 1672,
    height: 941,
  },
  "/images/partners/connected-network-investor.png": {
    steps: [400, 640, 960, 1440],
    width: 1672,
    height: 941,
  },
  "/images/partners/connected-network-landlord.png": {
    steps: [400, 640, 960, 1440],
    width: 1672,
    height: 941,
  },
  "/images/partners/connected-network-local-authority.png": {
    steps: [400, 640, 960, 1440],
    width: 1672,
    height: 941,
  },
  "/images/partners/connected-network-resident.png": {
    steps: [400, 640, 960, 1440],
    width: 1672,
    height: 941,
  },
  "/images/partners/connected-network-social-worker.png": {
    steps: [400, 640, 960, 1440],
    width: 1672,
    height: 941,
  },
  "/images/partners/connected-network-support-provider.png": {
    steps: [400, 640, 960, 1440],
    width: 1672,
    height: 941,
  },
  "/images/platform-finder.webp": {
    steps: [400, 640, 960, 1440],
    width: 1600,
    height: 862,
  },
  "/images/problem-thinking.webp": {
    steps: [400, 640, 960],
    width: 1024,
    height: 1536,
  },
  "/images/solution-speaking.webp": {
    steps: [400, 640, 960],
    width: 1024,
    height: 1536,
  },
  "/images/solution-street-blueprint.webp": {
    steps: [400, 640, 960],
    width: 1600,
    height: 900,
  },
  "/images/solution/house.webp": {
    steps: [],
    width: 453,
    height: 1100,
  },
  "/images/solution/hub.webp": {
    steps: [400, 640],
    width: 846,
    height: 620,
  },
  "/images/solution/trio.webp": {
    steps: [400, 640],
    width: 829,
    height: 620,
  },
  "/images/steps/assess.webp": {
    steps: [],
    width: 360,
    height: 360,
  },
  "/images/steps/managed.webp": {
    steps: [],
    width: 360,
    height: 360,
  },
  "/images/steps/reserve.webp": {
    steps: [],
    width: 360,
    height: 360,
  },
  "/images/steps/search.webp": {
    steps: [],
    width: 360,
    height: 360,
  },
  "/images/team/callum-saxon.webp": {
    steps: [],
    width: 440,
    height: 440,
  },
  "/images/team/israel-silgram-lead.webp": {
    steps: [400, 640],
    width: 880,
    height: 1100,
  },
  "/images/team/israel-silgram.webp": {
    steps: [],
    width: 440,
    height: 440,
  },
  "/images/team/jonathan-elton.webp": {
    steps: [],
    width: 440,
    height: 440,
  },
  "/images/team/maria-avallone.webp": {
    steps: [],
    width: 440,
    height: 440,
  },
  "/images/team/shahab-jamali.webp": {
    steps: [],
    width: 440,
    height: 440,
  },
  "/images/why-estate-aerial.webp": {
    steps: [400, 640, 960],
    width: 1600,
    height: 640,
  },
};
