/**
 * Council and data-provider credits, plus the platform's own coverage
 * figures.
 *
 * Everything here was copied from the production site at
 * `Impact-Investment-Platform/iip-frontend/iip-web` rather than rebuilt:
 * the council list from `src/components/marketing/CommissioningStrip.jsx`,
 * the data sources from `src/lib/dataSources.js`, and the artwork from
 * `public/logos/` with filenames unchanged.
 *
 * The disclaimers below are the reason this can ship at all. Council crests
 * are protected marks and a wall of them reads as endorsement unless it says
 * otherwise, and OpenStreetMap's ODbL *requires* attribution wherever its
 * data is credited. None of these lines is decoration — do not trim them to
 * make a layout fit.
 */

export interface LogoCredit {
  name: string;
  logo: string;
}

/**
 * The 18 councils whose published commissioning briefs shape what the
 * platform sources. Every entry has artwork — a council without a logo is
 * left out rather than shown as bare text.
 *
 * The `-128.webp` files are derivatives generated by the old repo's
 * `e2e/council-logo-optimise.mjs` at 2× the render height: aspect preserved,
 * no crop and no recolour, so no protected mark is altered.
 */
export const commissioningCouncils: LogoCredit[] = [
  {
    name: "North East Lincolnshire Council",
    logo: "/images/logos/councils/north-east-lincolnshire.svg",
  },
  { name: "Newcastle City Council", logo: "/images/logos/councils/newcastle-128.webp" },
  { name: "Sunderland City Council", logo: "/images/logos/councils/sunderland-128.webp" },
  { name: "Hartlepool Borough Council", logo: "/images/logos/councils/hartlepool-128.webp" },
  { name: "Middlesbrough Council", logo: "/images/logos/councils/middlesbrough-128.webp" },
  {
    name: "Stockton-on-Tees Borough Council",
    logo: "/images/logos/councils/stockton-on-tees-128.webp",
  },
  { name: "County Durham Council", logo: "/images/logos/councils/county-durham-128.webp" },
  { name: "Manchester City Council", logo: "/images/logos/councils/manchester-128.webp" },
  { name: "Salford City Council", logo: "/images/logos/councils/salford-128.webp" },
  { name: "Liverpool City Council", logo: "/images/logos/councils/liverpool-128.webp" },
  { name: "Wirral Council", logo: "/images/logos/councils/wirral-128.webp" },
  { name: "Lancashire County Council", logo: "/images/logos/councils/lancashire-128.webp" },
  { name: "Cumberland Council", logo: "/images/logos/councils/cumberland.svg" },
  {
    name: "Westmorland and Furness Council",
    logo: "/images/logos/councils/westmorland-and-furness-128.webp",
  },
  { name: "Nottingham City Council", logo: "/images/logos/councils/nottingham-128.webp" },
  { name: "Derby City Council", logo: "/images/logos/councils/derby-128.webp" },
  { name: "Lincolnshire County Council", logo: "/images/logos/councils/lincolnshire-128.webp" },
  {
    name: "East Riding of Yorkshire Council",
    logo: "/images/logos/councils/east-riding-of-yorkshire-128.webp",
  },
];

export const councilsEyebrow = "Built around what local authorities are commissioning";

/** Verbatim from the source component. Never shorten this. */
export const councilsDisclaimer =
  "These are 18 of the ~296 local authorities in England, in the areas we source most. Their logos indicate the commissioning briefs we build around — not a partnership, endorsement or approval by any council.";

export interface DataSource extends LogoCredit {
  id: string;
  /** Rides the image alt — what the platform actually reads from it. */
  blurb: string;
  /** Intrinsic artwork size, so a lazy tile reserves its true width. */
  artwork: { w: number; h: number };
}

/**
 * A logo here is a claim that the running platform queries that source.
 * Companies House is deliberately absent: the old repo records that its
 * integration is key-gated on a variable never provisioned in production,
 * so crediting it would claim something the platform does not do.
 */
export const dataSources: DataSource[] = [
  {
    id: "land-registry",
    name: "HM Land Registry",
    logo: "/images/logos/data/hm-land-registry.svg",
    artwork: { w: 440, h: 200 },
    blurb: "Sold prices · price-paid comparables",
  },
  {
    id: "ons",
    name: "Office for National Statistics",
    logo: "/images/logos/data/ons.svg",
    artwork: { w: 595.3, h: 116.3 },
    blurb: "Population estimates & private-rent trends",
  },
  {
    id: "postcodes-io",
    name: "postcodes.io",
    logo: "/images/logos/data/postcodes-io.svg",
    artwork: { w: 440, h: 200 },
    blurb: "Postcode validation & geocoding",
  },
  {
    id: "openstreetmap",
    name: "OpenStreetMap",
    logo: "/images/logos/data/openstreetmap.svg",
    artwork: { w: 440, h: 200 },
    blurb: "Walkable amenities around a home",
  },
  {
    id: "epc-register",
    name: "Energy Performance Register",
    logo: "/images/logos/data/epc-register.svg",
    artwork: { w: 440, h: 200 },
    blurb: "Energy ratings · floor area",
  },
];

export const dataSourcesEyebrow = "Powered by authoritative UK data";

/** Both lines are legal, not decorative. */
export const dataSourcesDisclaimer =
  "Public data used under licence. These publishers do not endorse this platform.";
/** ODbL requires the contributor credit *and* an indication of the licence. */
export const openStreetMapAttribution = "© OpenStreetMap contributors · ODbL";

export interface PlatformStat {
  value: string;
  label: string;
  detail: string;
  /** The middle card is filled — teal, never orange. Orange is for actions. */
  emphasis?: boolean;
}

/*
 * ⚠️ THESE FIGURES ARE A STATIC SNAPSHOT, NOT LIVE.
 *
 * On the production site these three tiles read `GET /api/public/platform-stats`
 * and follow an honest ladder: skeleton while in flight, the banded figure on
 * success, and the literal word "Growing" on failure — never a fabricated
 * number. This repo has no backend and no such endpoint, so the values below
 * are transcribed from what that site was displaying.
 *
 *   Source:    Impact-Investment-Platform production site, HomeStatsBand
 *   Recorded:  3 August 2026
 *
 * They will drift. Either point the caption at a real endpoint or change the
 * "live from our platform" line, because as it stands the caption claims
 * something the page cannot currently do.
 */
export const platformStats: PlatformStat[] = [
  {
    value: "193,000+",
    label: "homes sourced & analysed",
    detail: "Sourced across the UK, each run through our analysis.",
  },
  {
    value: "634,000+",
    label: "potential homing opportunities",
    detail: "Counted as the bedrooms across those homes — each a potential supported room.",
    emphasis: true,
  },
  {
    value: "1,693",
    label: "towns & areas covered",
    detail: "Towns and areas with at least one home sourced.",
  },
];

export const platformStatsSource = "live from our platform";
