/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PartnerWithBrokerRouteImport } from './routes/partner-with-broker'
import { Route as PartnerWithCareProviderRouteImport } from './routes/partner-with-care-provider'
import { Route as PartnerWithDeveloperRouteImport } from './routes/partner-with-developer'
import { Route as PartnerWithHousingAssociationRouteImport } from './routes/partner-with-housing-association'
import { Route as PartnerWithInvestorRouteImport } from './routes/partner-with-investor'
import { Route as PartnerWithLandlordRouteImport } from './routes/partner-with-landlord'
import { Route as PartnerWithLocalAuthorityRouteImport } from './routes/partner-with-local-authority'
import { Route as PartnerWithResidentRouteImport } from './routes/partner-with-resident'
import { Route as PartnerWithSocialWorkerRouteImport } from './routes/partner-with-social-worker'
import { Route as PartnerWithSupportProviderRouteImport } from './routes/partner-with-support-provider'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as TheProblemRouteImport } from './routes/the-problem'
import { Route as ApiEnquiryRouteImport } from './routes/api/enquiry'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerWithBrokerRoute = PartnerWithBrokerRouteImport.update({
  id: '/partner-with-broker',
  path: '/partner-with-broker',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerWithCareProviderRoute = PartnerWithCareProviderRouteImport.update({
  id: '/partner-with-care-provider',
  path: '/partner-with-care-provider',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerWithDeveloperRoute = PartnerWithDeveloperRouteImport.update({
  id: '/partner-with-developer',
  path: '/partner-with-developer',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerWithHousingAssociationRoute =
  PartnerWithHousingAssociationRouteImport.update({
    id: '/partner-with-housing-association',
    path: '/partner-with-housing-association',
    getParentRoute: () => rootRouteImport,
  } as any)
const PartnerWithInvestorRoute = PartnerWithInvestorRouteImport.update({
  id: '/partner-with-investor',
  path: '/partner-with-investor',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerWithLandlordRoute = PartnerWithLandlordRouteImport.update({
  id: '/partner-with-landlord',
  path: '/partner-with-landlord',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerWithLocalAuthorityRoute =
  PartnerWithLocalAuthorityRouteImport.update({
    id: '/partner-with-local-authority',
    path: '/partner-with-local-authority',
    getParentRoute: () => rootRouteImport,
  } as any)
const PartnerWithResidentRoute = PartnerWithResidentRouteImport.update({
  id: '/partner-with-resident',
  path: '/partner-with-resident',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerWithSocialWorkerRoute = PartnerWithSocialWorkerRouteImport.update({
  id: '/partner-with-social-worker',
  path: '/partner-with-social-worker',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerWithSupportProviderRoute =
  PartnerWithSupportProviderRouteImport.update({
    id: '/partner-with-support-provider',
    path: '/partner-with-support-provider',
    getParentRoute: () => rootRouteImport,
  } as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const TheProblemRoute = TheProblemRouteImport.update({
  id: '/the-problem',
  path: '/the-problem',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEnquiryRoute = ApiEnquiryRouteImport.update({
  id: '/api/enquiry',
  path: '/api/enquiry',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/partner-with-broker': typeof PartnerWithBrokerRoute
  '/partner-with-care-provider': typeof PartnerWithCareProviderRoute
  '/partner-with-developer': typeof PartnerWithDeveloperRoute
  '/partner-with-housing-association': typeof PartnerWithHousingAssociationRoute
  '/partner-with-investor': typeof PartnerWithInvestorRoute
  '/partner-with-landlord': typeof PartnerWithLandlordRoute
  '/partner-with-local-authority': typeof PartnerWithLocalAuthorityRoute
  '/partner-with-resident': typeof PartnerWithResidentRoute
  '/partner-with-social-worker': typeof PartnerWithSocialWorkerRoute
  '/partner-with-support-provider': typeof PartnerWithSupportProviderRoute
  '/partners': typeof PartnersRoute
  '/platform': typeof PlatformRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solutions': typeof SolutionsRoute
  '/the-problem': typeof TheProblemRoute
  '/api/enquiry': typeof ApiEnquiryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/partner-with-broker': typeof PartnerWithBrokerRoute
  '/partner-with-care-provider': typeof PartnerWithCareProviderRoute
  '/partner-with-developer': typeof PartnerWithDeveloperRoute
  '/partner-with-housing-association': typeof PartnerWithHousingAssociationRoute
  '/partner-with-investor': typeof PartnerWithInvestorRoute
  '/partner-with-landlord': typeof PartnerWithLandlordRoute
  '/partner-with-local-authority': typeof PartnerWithLocalAuthorityRoute
  '/partner-with-resident': typeof PartnerWithResidentRoute
  '/partner-with-social-worker': typeof PartnerWithSocialWorkerRoute
  '/partner-with-support-provider': typeof PartnerWithSupportProviderRoute
  '/partners': typeof PartnersRoute
  '/platform': typeof PlatformRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solutions': typeof SolutionsRoute
  '/the-problem': typeof TheProblemRoute
  '/api/enquiry': typeof ApiEnquiryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/partner-with-broker': typeof PartnerWithBrokerRoute
  '/partner-with-care-provider': typeof PartnerWithCareProviderRoute
  '/partner-with-developer': typeof PartnerWithDeveloperRoute
  '/partner-with-housing-association': typeof PartnerWithHousingAssociationRoute
  '/partner-with-investor': typeof PartnerWithInvestorRoute
  '/partner-with-landlord': typeof PartnerWithLandlordRoute
  '/partner-with-local-authority': typeof PartnerWithLocalAuthorityRoute
  '/partner-with-resident': typeof PartnerWithResidentRoute
  '/partner-with-social-worker': typeof PartnerWithSocialWorkerRoute
  '/partner-with-support-provider': typeof PartnerWithSupportProviderRoute
  '/partners': typeof PartnersRoute
  '/platform': typeof PlatformRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solutions': typeof SolutionsRoute
  '/the-problem': typeof TheProblemRoute
  '/api/enquiry': typeof ApiEnquiryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/partner-with-broker'
    | '/partner-with-care-provider'
    | '/partner-with-developer'
    | '/partner-with-housing-association'
    | '/partner-with-investor'
    | '/partner-with-landlord'
    | '/partner-with-local-authority'
    | '/partner-with-resident'
    | '/partner-with-social-worker'
    | '/partner-with-support-provider'
    | '/partners'
    | '/platform'
    | '/sitemap.xml'
    | '/solutions'
    | '/the-problem'
    | '/api/enquiry'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/partner-with-broker'
    | '/partner-with-care-provider'
    | '/partner-with-developer'
    | '/partner-with-housing-association'
    | '/partner-with-investor'
    | '/partner-with-landlord'
    | '/partner-with-local-authority'
    | '/partner-with-resident'
    | '/partner-with-social-worker'
    | '/partner-with-support-provider'
    | '/partners'
    | '/platform'
    | '/sitemap.xml'
    | '/solutions'
    | '/the-problem'
    | '/api/enquiry'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/partner-with-broker'
    | '/partner-with-care-provider'
    | '/partner-with-developer'
    | '/partner-with-housing-association'
    | '/partner-with-investor'
    | '/partner-with-landlord'
    | '/partner-with-local-authority'
    | '/partner-with-resident'
    | '/partner-with-social-worker'
    | '/partner-with-support-provider'
    | '/partners'
    | '/platform'
    | '/sitemap.xml'
    | '/solutions'
    | '/the-problem'
    | '/api/enquiry'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  PartnerWithBrokerRoute: typeof PartnerWithBrokerRoute
  PartnerWithCareProviderRoute: typeof PartnerWithCareProviderRoute
  PartnerWithDeveloperRoute: typeof PartnerWithDeveloperRoute
  PartnerWithHousingAssociationRoute: typeof PartnerWithHousingAssociationRoute
  PartnerWithInvestorRoute: typeof PartnerWithInvestorRoute
  PartnerWithLandlordRoute: typeof PartnerWithLandlordRoute
  PartnerWithLocalAuthorityRoute: typeof PartnerWithLocalAuthorityRoute
  PartnerWithResidentRoute: typeof PartnerWithResidentRoute
  PartnerWithSocialWorkerRoute: typeof PartnerWithSocialWorkerRoute
  PartnerWithSupportProviderRoute: typeof PartnerWithSupportProviderRoute
  PartnersRoute: typeof PartnersRoute
  PlatformRoute: typeof PlatformRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SolutionsRoute: typeof SolutionsRoute
  TheProblemRoute: typeof TheProblemRoute
  ApiEnquiryRoute: typeof ApiEnquiryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner-with-broker': {
      id: '/partner-with-broker'
      path: '/partner-with-broker'
      fullPath: '/partner-with-broker'
      preLoaderRoute: typeof PartnerWithBrokerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner-with-care-provider': {
      id: '/partner-with-care-provider'
      path: '/partner-with-care-provider'
      fullPath: '/partner-with-care-provider'
      preLoaderRoute: typeof PartnerWithCareProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner-with-developer': {
      id: '/partner-with-developer'
      path: '/partner-with-developer'
      fullPath: '/partner-with-developer'
      preLoaderRoute: typeof PartnerWithDeveloperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner-with-housing-association': {
      id: '/partner-with-housing-association'
      path: '/partner-with-housing-association'
      fullPath: '/partner-with-housing-association'
      preLoaderRoute: typeof PartnerWithHousingAssociationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner-with-investor': {
      id: '/partner-with-investor'
      path: '/partner-with-investor'
      fullPath: '/partner-with-investor'
      preLoaderRoute: typeof PartnerWithInvestorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner-with-landlord': {
      id: '/partner-with-landlord'
      path: '/partner-with-landlord'
      fullPath: '/partner-with-landlord'
      preLoaderRoute: typeof PartnerWithLandlordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner-with-local-authority': {
      id: '/partner-with-local-authority'
      path: '/partner-with-local-authority'
      fullPath: '/partner-with-local-authority'
      preLoaderRoute: typeof PartnerWithLocalAuthorityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner-with-resident': {
      id: '/partner-with-resident'
      path: '/partner-with-resident'
      fullPath: '/partner-with-resident'
      preLoaderRoute: typeof PartnerWithResidentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner-with-social-worker': {
      id: '/partner-with-social-worker'
      path: '/partner-with-social-worker'
      fullPath: '/partner-with-social-worker'
      preLoaderRoute: typeof PartnerWithSocialWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner-with-support-provider': {
      id: '/partner-with-support-provider'
      path: '/partner-with-support-provider'
      fullPath: '/partner-with-support-provider'
      preLoaderRoute: typeof PartnerWithSupportProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/the-problem': {
      id: '/the-problem'
      path: '/the-problem'
      fullPath: '/the-problem'
      preLoaderRoute: typeof TheProblemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/enquiry': {
      id: '/api/enquiry'
      path: '/api/enquiry'
      fullPath: '/api/enquiry'
      preLoaderRoute: typeof ApiEnquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  PartnerWithBrokerRoute: PartnerWithBrokerRoute,
  PartnerWithCareProviderRoute: PartnerWithCareProviderRoute,
  PartnerWithDeveloperRoute: PartnerWithDeveloperRoute,
  PartnerWithHousingAssociationRoute: PartnerWithHousingAssociationRoute,
  PartnerWithInvestorRoute: PartnerWithInvestorRoute,
  PartnerWithLandlordRoute: PartnerWithLandlordRoute,
  PartnerWithLocalAuthorityRoute: PartnerWithLocalAuthorityRoute,
  PartnerWithResidentRoute: PartnerWithResidentRoute,
  PartnerWithSocialWorkerRoute: PartnerWithSocialWorkerRoute,
  PartnerWithSupportProviderRoute: PartnerWithSupportProviderRoute,
  PartnersRoute: PartnersRoute,
  PlatformRoute: PlatformRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SolutionsRoute: SolutionsRoute,
  TheProblemRoute: TheProblemRoute,
  ApiEnquiryRoute: ApiEnquiryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
